---
title: "script1121"
author: "Guangze Sun"
date: "2024-11-22"
output: html_document
---

https://docs.google.com/document/d/1Q9j6WZ54YXz71wHLA6temmkFtY7Rwml2vAGG0MKIdsA/

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "null", echo = TRUE)
Sys.setlocale("LC_TIME", "C")
```

```{r}
library(tidyverse)
library(stringr)
library(sf)
```

```{r}
data <- read.csv('trains_train.csv') %>% 
  filter(!(to %in% c("000000000", "(null)"))) %>% 
  filter(!(from %in% c("(null)"))) %>%
  mutate(
    OD = paste(from, to, sep = "/"),
    type = ifelse(
      str_detect(vehicle, "[A-Za-z]"),
      str_extract(vehicle, "^[A-Za-z]+"),
      "Extra"
    ),
    occupancy_numeric = case_when(
      occupancy == "high" ~ 2,
      occupancy == "medium" ~ 1,
      occupancy == "low" ~ 0)
  ) %>%
  dplyr::select(-connection, -occupancy)
```

```{r}
stations <- read.csv('stations.csv') %>%
  mutate(
    code = str_extract(URI, "[^/]{9}$"),
    Weekday = as.numeric(Weekday),
    Weekend = rowMeans(cbind(as.numeric(Saturday), as.numeric(Sunday)), na.rm = TRUE) 
  ) %>%
  filter(country.code == "be") %>% 
  select(code, name, longitude, latitude, Weekday, Weekend) %>% 
  filter(code %in% unique(c(data$from, data$to)))

stations_sf <- stations %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326)

ggplot(data = stations_sf) +
  geom_sf(color = "grey20", size = 2) +
  theme_minimal() +
  labs(title = "Train Stations",
       x = "Longitude",
       y = "Latitude")
```

```{r}
from_avg <- data %>%
  group_by(from) %>%
  summarize(from_avg = mean(occupancy_numeric, na.rm = TRUE))

to_avg <- data %>%
  group_by(to) %>%
  summarize(to_avg = mean(occupancy_numeric, na.rm = TRUE))

stations <- stations %>%
  left_join(from_avg, by = c("code" = "from")) %>%
  left_join(to_avg, by = c("code" = "to"))

stations_sf <- stations %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326)

ggplot(data = stations_sf %>% filter(country == "be") %>% filter(!is.na(from_avg))) +
  geom_sf(aes(color = from_avg), size = 2) +  
  scale_color_gradient(low = "grey80", high = "firebrick") +
  theme_minimal() +
  labs(title = "Average Occupancy: Origin",
       color = "Origin Avg",
       x = "Longitude",
       y = "Latitude")

ggplot(data = stations_sf %>% filter(country == "be") %>% filter(!is.na(to_avg))) +
  geom_sf(aes(color = to_avg), size = 2) +  
  scale_color_gradient(low = "grey80", high = "firebrick") +
  theme_minimal() +
  labs(title = "Average Occupancy: Destination",
       color = "Dest. Avg",
       x = "Longitude",
       y = "Latitude")
```

```{r}
od_data <- data %>%
  group_by(OD) %>%
  #filter(n() > 3) %>%  
  summarize(
    avg_occupancy = mean(occupancy_numeric, na.rm = TRUE),
    from = first(from),
    to = first(to)
  )

od_with_coords <- od_data %>%
  left_join(stations, by = c("from" = "code")) %>%
  rename(from_long = longitude, from_lat = latitude) %>%
  left_join(stations, by = c("to" = "code")) %>%
  rename(to_long = longitude, to_lat = latitude)

od_lines <- od_with_coords %>%
  filter(!is.na(from_long) & !is.na(to_long)) %>%  
  rowwise() %>%
  mutate(geometry = st_sfc(st_linestring(matrix(c(from_long, from_lat, to_long, to_lat), ncol = 2, byrow = TRUE)), crs = 4326)) %>%
  st_as_sf()

bbox <- stations_sf %>%
  filter(country == "be") %>%
  st_bbox()

ggplot() +
  geom_sf(data = stations_sf %>% filter(country == "be"), color = "black", size = 2) +
  geom_sf(data = od_lines, aes(color = avg_occupancy), size = 2, alpha = 0.7) +  
  scale_color_gradient(low = "grey80", high = "firebrick") +
  theme_minimal() +
  coord_sf(
    xlim = c(bbox["xmin"], bbox["xmax"]),
    ylim = c(bbox["ymin"], bbox["ymax"]),
    expand = FALSE
  ) +
  labs(title = "OD Connections with Avg Occupancy",
       x = "Longitude",
       y = "Latitude")


```