---
title: "Script 1204"
author: "Guangze Sun"
date: "2024-12-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Sys.setlocale("LC_TIME", "C")
```

```{r}
library(tidyverse)
library(sf)
library(gridExtra)
library(caret)
library(spdep)
library(plotROC)
library(pROC)
```

```{r}
data <- read.csv('trains_train.csv') %>% 
  filter(!(to %in% c("000000000", "(null)"))) %>% 
  filter(!(from %in% c("(null)"))) %>%
  mutate(
    OD = paste(from, to, sep = "/"),
    type = ifelse(
      str_detect(vehicle, "[A-Za-z]"),
      str_extract(vehicle, "^[A-Za-z]+"),
      "Extra"
    ),
    occupancy_classifier = case_when(
      occupancy == "high" ~ 1,
      TRUE ~ 0)
  ) %>%
  dplyr::select(-connection, -occupancy)
```

```{r}
data <- data %>%
  mutate(
    time_24hr = format(parse_date_time(trimws(time), orders = "HMS p"), "%H:%M:%S"),
    datetime_combined = ymd(date) + hms(time_24hr),
    interval60 = floor_date(datetime_combined, "hour"),
    #interval30 = floor_date(datetime_combined, "30 minutes"),
    hour = hour(interval60),
    #minute = minute(interval30),
    #halfhour = hour + ifelse(minute >= 30, 0.5, 0),
    dotw = wday(interval60, label = TRUE),
    is_weekend = ifelse(dotw %in% c("Sat", "Sun"), "Weekend", "Weekday"),
    date = ymd(date)
  )
```

```{r}
count <- data %>%
  group_by(dotw, hour) %>%
  summarise(count = n())

# count_half <- data %>%
#   group_by(dotw, halfhour) %>%
#   summarise(counthalf = n())

high_occupancy_count <- data %>%
  group_by(dotw, hour) %>%
  summarise(high_occupancy_count = sum(occupancy_classifier, na.rm = TRUE))

# high_occupancy_count_half <- data %>%
#   group_by(dotw, halfhour) %>%
#   summarise(high_occupancy_counthalf = sum(occupancy_classifier, na.rm = TRUE))

high_occupancy_rate <- data %>%
  group_by(dotw, hour) %>%
  summarise(high_occupancy_rate = mean(occupancy_classifier, na.rm = TRUE))

# high_occupancy_rate_half <- data %>%
#   group_by(dotw, halfhour) %>%
#   summarise(high_occupancy_ratehalf = mean(occupancy_classifier, na.rm = TRUE))


data <- data %>%
  left_join(count, by = c("dotw", "hour")) %>%
#  left_join(high_occupancy_count, by = c("dotw", "hour")) %>%
  left_join(high_occupancy_rate, by = c("dotw", "hour"))
# %>% left_join(count_half, by = c("dotw", "halfhour")) 
# %>% left_join(high_occupancy_count_half, by = c("dotw", "halfhour")) 
# %>% left_join(high_occupancy_rate_half, by = c("dotw", "halfhour")) 

```
```{r}
occupancy.Panel <- data %>% 
  group_by(date) %>%
  summarize(count = n(),
          high_occupancy_rate = mean(occupancy_classifier))

grid.arrange(
  ggplot(occupancy.Panel, aes(date, count)) + geom_line() + 
  labs(title="Count", x="Date", y="Count") + theme_minimal(),
  ggplot(occupancy.Panel, aes(date, high_occupancy_rate)) + geom_line() + 
  labs(title="High Occupancy Rate", x="Date", y="High Occupancy Rate") + theme_minimal(),
  top="Occupancy Data")

```

```{r}
ggplot(data %>% filter(count > 4), aes(x = dotw, y = hour, fill = high_occupancy_rate)) +
  geom_tile() + 
  scale_fill_gradient(low = "white", high = "red") +  
  labs(title = "High Occupancy Rate Across the Week",
       x = "Day of the Week",
       y = "Hour of the Day",
       fill = "High Occupancy Rate") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_reverse()
```

```{r}
weather <- read.csv('weather.csv')

weather <- weather %>%
  mutate(
    date = ymd(Time),             
    month_day = format(date, "%m-%d")  
  )


data <- data %>%
  mutate(month_day = format(date, "%m-%d")) %>%
  left_join(weather %>% select(month_day, Temperature, Precipitation), by = "month_day")
```

```{r}
weather.Panel <- data %>% 
  group_by(interval60) %>%
  summarize(Temperature = max(Temperature),
          Precipitation = max(Precipitation))

grid.arrange(
  ggplot(weather.Panel, aes(interval60,Temperature)) + geom_line() + 
  labs(title="Temperature", x="Hour", y="Temperature") + theme_minimal(),
  ggplot(weather.Panel, aes(interval60,Precipitation)) + geom_line() + 
    labs(title="Percipitation", x="Hour", y="Precipitation") + theme_minimal(),
  top="Weather Data")
```

```{r}
be <- st_read("be.shp") %>% st_transform(crs = 4326)
```

```{r}
stations <- read.csv('stations.csv') %>%
  mutate(
    code = str_extract(URI, "[^/]{9}$"),
    Weekday = as.numeric(Weekday),
    Weekend = rowMeans(cbind(as.numeric(Saturday), as.numeric(Sunday)), na.rm = TRUE)
  ) %>%
  filter(country.code == "be") %>% 
  select(code, name, longitude, latitude, Weekday, Weekend) %>% 
  filter(code %in% unique(c(data$from, data$to)))

from_avg <- data %>%
  group_by(from) %>%
  summarize(from_count = n(),
            from_avg = mean(occupancy_classifier, na.rm = TRUE))

to_avg <- data %>%
  group_by(to) %>%
  summarize(to_count = n(),
            to_avg = mean(occupancy_classifier, na.rm = TRUE))

stations <- stations %>%
  mutate(Overall = Weekday * 5/7 + Weekend * 2/7) %>%
  left_join(from_avg, by = c("code" = "from")) %>%
  left_join(to_avg, by = c("code" = "to")) %>%
  replace(is.na(.), 0) %>%
  mutate(overall_count = from_count + to_count,
         overall_avg = (from_avg * from_count + to_avg * to_count) / (from_count + to_count))

stations_sf <- stations %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326)

ggplot(data = stations_sf %>% filter(!is.na(from_avg))) +
  geom_sf(data = be, color = "white", alpha = 0.8) +
  geom_sf(aes(color = from_avg), size = 2) +  
  scale_color_gradient(low = "grey80", high = "firebrick") +
  theme_minimal() +
  labs(title = "Average Occupancy: Origin",
       color = "Origin Avg",
       x = "Longitude",
       y = "Latitude")

ggplot(data = stations_sf %>% filter(!is.na(to_avg))) +
  geom_sf(data = be, color = "white", alpha = 0.8) +
  geom_sf(aes(color = to_avg), size = 2) +  
  scale_color_gradient(low = "grey80", high = "firebrick") +
  theme_minimal() +
  labs(title = "Average Occupancy: Destination",
       color = "Dest. Avg",
       x = "Longitude",
       y = "Latitude")

ggplot(data = stations_sf %>% filter(!is.na(overall_avg))) +
  geom_sf(data = be, color = "white", alpha = 0.8) +
  geom_sf(aes(color = to_avg), size = 2) +  
  scale_color_gradient(low = "grey80", high = "firebrick") +
  theme_minimal() +
  labs(title = "Average Occupancy by Station",
       color = "Overall Avg",
       x = "Longitude",
       y = "Latitude")

ggplot(data = stations %>% filter(overall_count > 4)) +
  geom_point(aes(Overall, overall_avg), size = 2) +  
  theme_minimal() +
  labs(title = "Passenger Count vs Overall Occupancy",
       x = "Passenger Count",
       y = "Overall Occupancy")
```

```{r}
stations <- stations %>%
  mutate(level = case_when(
    Overall > 10000 ~ "A",
    Overall > 1000 & Overall <= 10000 ~ "B",
    Overall <= 1000 ~ "C"
  ))

data <- data %>%
  filter(from %in% stations$code & to %in% stations$code) %>%
  left_join(stations %>% select(code, level) %>% rename(from_level = level), 
            by = c("from" = "code")) %>%
  left_join(stations %>% select(code, level) %>% rename(to_level = level), 
            by = c("to" = "code")) %>%
  mutate(OD_level = paste(from_level, to_level, sep = "/"))

data <- data %>%
  left_join(stations %>% select(code, Overall) %>% rename(from_passenger = Overall), 
            by = c("from" = "code")) %>%
  left_join(stations %>% select(code, Overall) %>% rename(to_passenger = Overall), 
            by = c("to" = "code")) %>%
  mutate(OD_passenger = log(from_passenger) * log(to_passenger))

data <- data %>%
  mutate(time_period = case_when(
    hour >= 6 & hour <= 9  ~ "Morning",
    hour >= 10 & hour <= 15 ~ "Noon",
    hour >= 16 & hour <= 21 ~ "Evening",
    TRUE ~ "Night"
  )) %>%  
  mutate(day_time = paste(as.character(dotw), time_period, sep = "/"))

```

```{r}
od_data <- data %>%
  group_by(OD) %>%
  #filter(n() > 3) %>%  
  summarize(
    count = n(),
    avg_occupancy = mean(occupancy_classifier, na.rm = TRUE),
    from = first(from),
    to = first(to)
  )

od_with_coords <- od_data %>%
  left_join(stations, by = c("from" = "code")) %>%
  rename(from_long = longitude, from_lat = latitude) %>%
  left_join(stations, by = c("to" = "code")) %>%
  rename(to_long = longitude, to_lat = latitude)

od_lines <- od_with_coords %>%
  filter(!is.na(from_long) & !is.na(to_long)) %>%  
  rowwise() %>%
  mutate(geometry = st_sfc(st_linestring(matrix(c(from_long, from_lat, to_long, to_lat), ncol = 2, byrow = TRUE)), crs = 4326)) %>%
  st_as_sf()

ggplot() +
  geom_sf(data = be, color = "white", alpha = 0.5) +
  geom_sf(data = stations_sf, color = "black", size = 1.5) +
  geom_sf(data = od_lines, aes(color = avg_occupancy, alpha = count), linewidth = 1) + 
  scale_alpha(range = c(0.4, 1), guide = "legend") +
  scale_color_gradient(low = "grey80", high = "firebrick") +
  theme_minimal() +
  labs(title = "OD Connections with Avg Occupancy",
       x = "Longitude",
       y = "Latitude")

```

```{r}
data <- data %>%
  mutate(type = case_when(
    type %in% c("ic") ~ "IC",        
    type %in% c("ICT", "ICE", "THA", "TRN", "Extra") ~ "Other", 
    TRUE ~ type                                   
  ))

train_type <- data %>%
  group_by(type) %>%
  summarize(count = n(),
            avg = mean(occupancy_classifier, na.rm = TRUE))

ggplot(train_type, aes(x = fct_reorder(type, avg, .desc = TRUE), y = avg)) +
  geom_col(position = position_dodge(width = 0.7), show.legend = FALSE, width = 0.7) +
  labs(
    title = "Average Occupancy by Train Type",
    x = "Train Type",
    y = "Average Occupancy"
  ) +
  theme_minimal()
```

```{r}
schedules <- read.csv("OctSchedules.txt", header = F)
freq <- read.csv("stations_freq.csv")
schedules <- schedules %>% 
  dplyr::select(V1, V9, V10, V14) %>% 
  rename(date = V1, arrive_time = V9, depart_time = V10, station = V14) %>% 
  mutate(time = ifelse(depart_time == "", arrive_time, depart_time)) %>%
  dplyr::select(-depart_time, -arrive_time) %>%
  mutate(
    date = dmy(date),
    datetime = as.POSIXct(paste(date, time), format = "%Y-%m-%d %H:%M:%S")
  ) %>%
  dplyr::select(-date, -time) %>%
  left_join(freq %>% select(station, name), by = "station") %>% 
  na.omit() %>% 
  dplyr::select(-station) %>%
  left_join(stations %>% select(name, code), by = "name") %>% 
  dplyr::select(-name)

start_date <- as.POSIXct("2016-10-23 00:00:00")

data <- data %>%
  mutate(
    mapped_date = as.Date(start_date) + ((as.numeric(as.Date(datetime_combined) - as.Date(start_date))) %% 7),
    mapped_datetime = as.POSIXct(paste(mapped_date, format(datetime_combined, "%H:%M:%S")), format = "%Y-%m-%d %H:%M:%S")
  )

data <- data %>%
  rowwise() %>% 
  # mutate(
  #   freq_from = sum(
  #     schedules$datetime >= (mapped_datetime - hours(1)) &  
  #       schedules$datetime <= (mapped_datetime + hours(1)) &  
  #       schedules$code == from                                    
  #   ),
  #   freq_to = sum(
  #     schedules$datetime >= (mapped_datetime - hours(1)) &  
  #       schedules$datetime <= (mapped_datetime + hours(1)) &  
  #       schedules$code == to                                    
  #   ),
  #   freq = (freq_from + freq_to) / 2
  # ) %>%
  mutate(
    freq_from = sum(
      schedules$datetime >= (mapped_datetime - minutes(30)) &  
        schedules$datetime <= (mapped_datetime + minutes(30)) &  
        schedules$code == from                                    
    ),
    freq_to = sum(
      schedules$datetime >= (mapped_datetime - minutes(30)) &  
        schedules$datetime <= (mapped_datetime + minutes(30)) &  
        schedules$code == to                                    
    ),
    freq = (freq_from + freq_to) / 2
  ) %>%
  ungroup() 

```

```{r}
data_model <- data %>% dplyr::select(occupancy_classifier, datetime_combined, dotw, hour,
                                     time_period, day_time,
                               from_level, to_level, OD_level, type,
                               Temperature, Precipitation, OD_passenger, from, to, freq) %>%
  mutate(dotw = as.character(dotw), hour = as.factor(hour))

set.seed(1234)
trainIndex <- createDataPartition(data_model$occupancy_classifier, p = 0.7, list = FALSE, times = 1)

dataTrain <- data_model[trainIndex, ]
dataTest <- data_model[-trainIndex, ]

# model <- glm(occupancy_classifier ~ .,
#                   data = dataTrain %>% 
#                     dplyr::select(-time_period, -day_time, -OD_level, -OD_passenger, -from, -to),
#                   family="binomial" (link="logit"))
# 
# summary(model)
# 
# model2 <- glm(occupancy_classifier ~ .,
#                   data = dataTrain %>% 
#                     dplyr::select(-dotw, -hour, -time_period, -from_level, -to_level, -OD_passenger, -from, -to),
#                   family="binomial" (link="logit"))
# 
# summary(model2)
# 
# model3 <- glm(occupancy_classifier ~ .,
#                   data = dataTrain %>% 
#                     dplyr::select(-dotw, -hour, -time_period, -from_level, -to_level, -OD_level, -Precipitation, -from, -to),
#                   family="binomial" (link="logit"))
# 
# summary(model3)
```

```{r}
from_sum <- dataTrain %>%
  group_by(from) %>%
  summarize(from_count = n(),
            from_sum = sum(occupancy_classifier, na.rm = TRUE))

to_sum <- dataTrain %>%
  group_by(to) %>%
  summarize(to_count = n(),
            to_sum = sum(occupancy_classifier, na.rm = TRUE))

stations_train <- stations_sf[,c(1,12)] %>%
  left_join(from_sum, by = c("code" = "from")) %>%
  left_join(to_sum, by = c("code" = "to")) %>%
  replace(is.na(.), 0) %>%
  mutate(overall_count = from_count + to_count,
         overall_sum = from_sum + to_sum)

coords <- st_coordinates(stations_train)

knn_nb <- knn2nb(knearneigh(coords, k = 5))

neighbor_results <- lapply(1:length(knn_nb), function(i) {
  neighbors <- knn_nb[[i]]
  
  overall_count_sum <- sum(stations_train$overall_count[neighbors], na.rm = TRUE)
  overall_sum_sum <- sum(stations_train$overall_sum[neighbors], na.rm = TRUE)
  
  return(data.frame(overall_count_sum = overall_count_sum, overall_sum_sum = overall_sum_sum))
})

neighbor_results_df <- do.call(rbind, neighbor_results)

stations_train <- stations_train %>%
  bind_cols(neighbor_results_df) %>%
  mutate(neighbor = overall_sum_sum / overall_count_sum) %>% 
  st_drop_geometry()

dataTrain <- dataTrain %>%
  left_join(stations_train %>% select(code, neighbor) %>% rename(from_neighbor = neighbor), 
            by = c("from" = "code")) %>%
  left_join(stations_train %>% select(code, neighbor) %>% rename(to_neighbor = neighbor), 
            by = c("to" = "code")) %>%
  mutate(OD_neighbor = (from_neighbor + to_neighbor)/2) 

# model4 <- glm(occupancy_classifier ~ .,
#                   data = dataTrain %>% 
#                     dplyr::select(-dotw, -hour, -time_period, -from_level, -to_level, -OD_level, -Precipitation, -from, -to, -from_neighbor, -to_neighbor),
#                   family="binomial" (link="logit"))
# 
# summary(model4)
```

```{r}
dataTrain <- dataTrain %>%
  mutate(
    mapped_date = as.Date(start_date) + ((as.numeric(as.Date(datetime_combined) - as.Date(start_date))) %% 7),
    mapped_datetime = as.POSIXct(paste(mapped_date, format(datetime_combined, "%H:%M:%S")), format = "%Y-%m-%d %H:%M:%S")
  )

datetime <- dataTrain %>%
  dplyr::select(occupancy_classifier, datetime_combined, mapped_datetime) %>%
  arrange(mapped_datetime) %>%  
  slice(1:20) %>%
  mutate(mapped_datetime = mapped_datetime + days(7)) %>%
  bind_rows(
    dataTrain %>%
      dplyr::select(occupancy_classifier, datetime_combined, mapped_datetime) %>%
      arrange(mapped_datetime) %>%
      slice((n() - 19):n()) %>%
      mutate(mapped_datetime = mapped_datetime - days(7))
  ) %>%
  bind_rows(dataTrain %>%
              dplyr::select(occupancy_classifier, datetime_combined, mapped_datetime))

datetime <- datetime %>%
  arrange(mapped_datetime)

dataTrain <- dataTrain %>%
  mutate(
    rolling_avg = map_dbl(1:n(), function(i) {
      distances <- abs(as.numeric(datetime$mapped_datetime - mapped_datetime[i]))
      nearest_indices <- order(distances)[1:20]
      mean(datetime$occupancy_classifier[nearest_indices], na.rm = TRUE)
    })
  )

model <- glm(occupancy_classifier ~ type + Temperature + OD_passenger + OD_neighbor + rolling_avg + freq,
                  data = dataTrain, family="binomial" (link="logit"))

summary(model)
```

```{r}
dataTest <- dataTest %>%
  left_join(stations_train %>% select(code, neighbor) %>% rename(from_neighbor = neighbor), 
            by = c("from" = "code")) %>%
  left_join(stations_train %>% select(code, neighbor) %>% rename(to_neighbor = neighbor), 
            by = c("to" = "code")) %>%
  mutate(OD_neighbor = (from_neighbor + to_neighbor)/2)

dataTest <- dataTest %>%
  mutate(
    mapped_date = as.Date(start_date) + ((as.numeric(as.Date(datetime_combined) - as.Date(start_date))) %% 7),
    mapped_datetime = as.POSIXct(paste(mapped_date, format(datetime_combined, "%H:%M:%S")), format = "%Y-%m-%d %H:%M:%S")
  )

dataTest <- dataTest %>%
  mutate(
    rolling_avg = map_dbl(1:n(), function(i) {
      distances <- abs(as.numeric(datetime$mapped_datetime - mapped_datetime[i]))
      nearest_indices <- order(distances)[1:20]
      mean(datetime$occupancy_classifier[nearest_indices], na.rm = TRUE)
    })
  )
```

```{r}
testProbs <- data.frame(Outcome = as.factor(dataTest$occupancy_classifier),
                        Probs = predict(model, dataTest, type= "response"))

auc_value <- auc(testProbs$Outcome, testProbs$Probs)

ggplot(testProbs, aes(d = as.numeric(Outcome), m = Probs)) +
  geom_roc(n.cuts = 50, labels = FALSE, colour = "#FE9900") +
  style_roc(theme = theme_grey) +
  geom_abline(slope = 1, intercept = 0, size = 1, color = 'grey') +
  geom_text(aes(x = 0, y = 0.9, label = paste("ROC:", round(auc_value, 4))), 
            colour = "black", size = 4, hjust = 0) +
  labs(title = "ROC Curve: Original Model") +
  theme(plot.caption = element_text(hjust = 0))
```

```{r}
# testProbs2 <- data.frame(Outcome = as.factor(dataTest$occupancy_classifier),
#                         Probs = predict(model8, dataTest, type= "response"))
# 
# auc_value <- auc(testProbs2$Outcome, testProbs2$Probs)
# 
# ggplot(testProbs2, aes(d = as.numeric(Outcome), m = Probs)) +
#   geom_roc(n.cuts = 50, labels = FALSE, colour = "#FE9900") +
#   style_roc(theme = theme_grey) +
#   geom_abline(slope = 1, intercept = 0, size = 1, color = 'grey') +
#   geom_text(aes(x = 0, y = 0.9, label = paste("ROC:", round(auc_value, 4))), 
#             colour = "black", size = 4, hjust = 0) +
#   labs(title = "ROC Curve: Engineered Model") +
#   theme(plot.caption = element_text(hjust = 0))
```

```{r}
threshold <- 0.34  

dataTest_factor <- dataTest %>%
  mutate(occupancy_classifier = factor(occupancy_classifier, 
                                       levels = c(0, 1), 
                                       labels = c("Low", "High")))

testProbs <- testProbs %>%
  mutate(
    Predicted = ifelse(Probs >= threshold, "High", "Low"),
    Predicted = factor(Predicted, levels = c("Low", "High")), 
    Outcome = dataTest_factor$occupancy_classifier
  )


confusion_matrix <- confusionMatrix(testProbs$Predicted, testProbs$Outcome, positive = "High")

print(confusion_matrix)

# testProbs2 <- testProbs2 %>%
#   mutate(
#     Predicted = ifelse(Probs >= threshold, "High", "Low"),
#     Predicted = factor(Predicted, levels = c("Low", "High")), 
#     Outcome = dataTest_factor$occupancy_classifier
#   )
# 
# 
# confusion_matrix <- confusionMatrix(testProbs2$Predicted, testProbs2$Outcome, positive = "High")
# 
# print(confusion_matrix)
```

```{r}
iterateThresholds <- function(data) {
  x = .01
  all_prediction <- data.frame()
  while (x <= 1) {
    
    this_prediction <-
      testProbs %>%
      mutate(predOutcome = ifelse(Probs > x, "High", "Low")) %>%
      count(predOutcome, Outcome) %>%
      summarize(True_Negative = sum(n[predOutcome=="Low" & Outcome=="Low"]),
                True_Positive = sum(n[predOutcome=="High" & Outcome=="High"]),
                False_Negative = sum(n[predOutcome=="Low" & Outcome=="High"]),
                False_Positive = sum(n[predOutcome=="High" & Outcome=="Low"])) %>%
      gather(Variable, Count) %>%
      mutate(Revenue =
               ifelse(Variable == "True_Negative", 0 * Count,
                      ifelse(Variable == "True_Positive", 2 * Count,
                             ifelse(Variable == "False_Negative", 0 * Count,
                                    ifelse(Variable == "False_Positive", (-1) * Count, 0)))),
             Threshold = x)
    
    all_prediction <- rbind(all_prediction, this_prediction)
    x <- x + .01
  }
  return(all_prediction)
}

whichThreshold <- iterateThresholds(testProbs)

whichThreshold_revenue <- 
  whichThreshold %>% 
  group_by(Threshold) %>% 
  summarize(Revenue = sum(Revenue))

optimal_threshold <- whichThreshold_revenue %>% 
  filter(Revenue == max(Revenue)) %>% 
  pull(Threshold)

ggplot(whichThreshold_revenue) +
  geom_line(aes(x = Threshold, y = Revenue), color = "#FF006A", size = 1) +
  geom_vline(xintercept = pull(arrange(whichThreshold_revenue, -Revenue)[1, 1]), 
             color = "#981FAC", size = 1, linetype = 3) +
  annotate("text", x = optimal_threshold[1], y = 0, 
           label = paste("Optimal Threshold:", optimal_threshold[1]), 
           hjust = -0.1, vjust = -0.5, color = "black", size = 4) +
  labs(title = "Model Revenues By Threshold For Test Sample",
       subtitle = "Vertical Line Denotes Optimal Threshold") +
  theme(plot.caption = element_text(hjust = 0))
```

```{r}
results <- list()

for (i in 1:100) {
  
set.seed(606+i)
trainIndex <- createDataPartition(data_model$occupancy_classifier, p = 0.7, list = FALSE, times = 1)

dataTrain <- data_model[trainIndex, ]
dataTest <- data_model[-trainIndex, ]

from_sum <- dataTrain %>%
  group_by(from) %>%
  summarize(from_count = n(),
            from_sum = sum(occupancy_classifier, na.rm = TRUE))

to_sum <- dataTrain %>%
  group_by(to) %>%
  summarize(to_count = n(),
            to_sum = sum(occupancy_classifier, na.rm = TRUE))

stations_train <- stations_sf[,c(1,12)] %>%
  left_join(from_sum, by = c("code" = "from")) %>%
  left_join(to_sum, by = c("code" = "to")) %>%
  replace(is.na(.), 0) %>%
  mutate(overall_count = from_count + to_count,
         overall_sum = from_sum + to_sum)

coords <- st_coordinates(stations_train)

knn_nb <- knn2nb(knearneigh(coords, k = 5))

neighbor_results <- lapply(1:length(knn_nb), function(i) {
  neighbors <- knn_nb[[i]]
  
  overall_count_sum <- sum(stations_train$overall_count[neighbors], na.rm = TRUE)
  overall_sum_sum <- sum(stations_train$overall_sum[neighbors], na.rm = TRUE)
  
  return(data.frame(overall_count_sum = overall_count_sum, overall_sum_sum = overall_sum_sum))
})

neighbor_results_df <- do.call(rbind, neighbor_results)

stations_train <- stations_train %>%
  bind_cols(neighbor_results_df) %>%
  mutate(neighbor = overall_sum_sum / overall_count_sum) %>% 
  st_drop_geometry()

dataTrain <- dataTrain %>%
  left_join(stations_train %>% select(code, neighbor) %>% rename(from_neighbor = neighbor), 
            by = c("from" = "code")) %>%
  left_join(stations_train %>% select(code, neighbor) %>% rename(to_neighbor = neighbor), 
            by = c("to" = "code")) %>%
  mutate(OD_neighbor = (from_neighbor + to_neighbor)/2) 

dataTrain <- dataTrain %>%
  mutate(
    mapped_date = as.Date(start_date) + ((as.numeric(as.Date(datetime_combined) - as.Date(start_date))) %% 7),
    mapped_datetime = as.POSIXct(paste(mapped_date, format(datetime_combined, "%H:%M:%S")), format = "%Y-%m-%d %H:%M:%S")
  )

datetime <- dataTrain %>%
  dplyr::select(occupancy_classifier, datetime_combined, mapped_datetime) %>%
  arrange(mapped_datetime) %>%  
  slice(1:20) %>%
  mutate(mapped_datetime = mapped_datetime + days(7)) %>%
  bind_rows(
    dataTrain %>%
      dplyr::select(occupancy_classifier, datetime_combined, mapped_datetime) %>%
      arrange(mapped_datetime) %>%
      slice((n() - 19):n()) %>%
      mutate(mapped_datetime = mapped_datetime - days(7))
  ) %>%
  bind_rows(dataTrain %>%
              dplyr::select(occupancy_classifier, datetime_combined, mapped_datetime))

datetime <- datetime %>%
  arrange(mapped_datetime)

dataTrain <- dataTrain %>%
  mutate(
    rolling_avg = map_dbl(1:n(), function(i) {
      distances <- abs(as.numeric(datetime$mapped_datetime - mapped_datetime[i]))
      nearest_indices <- order(distances)[1:20]
      mean(datetime$occupancy_classifier[nearest_indices], na.rm = TRUE)
    })
  )

model <- glm(occupancy_classifier ~ type + Temperature + OD_passenger + OD_neighbor + rolling_avg + freq,
             data = dataTrain, family="binomial" (link="logit"))

dataTest <- dataTest %>%
  left_join(stations_train %>% select(code, neighbor) %>% rename(from_neighbor = neighbor), 
            by = c("from" = "code")) %>%
  left_join(stations_train %>% select(code, neighbor) %>% rename(to_neighbor = neighbor), 
            by = c("to" = "code")) %>%
  mutate(OD_neighbor = (from_neighbor + to_neighbor)/2)

dataTest <- dataTest %>%
  mutate(
    mapped_date = as.Date(start_date) + ((as.numeric(as.Date(datetime_combined) - as.Date(start_date))) %% 7),
    mapped_datetime = as.POSIXct(paste(mapped_date, format(datetime_combined, "%H:%M:%S")), format = "%Y-%m-%d %H:%M:%S")
  )

dataTest <- dataTest %>%
  mutate(
    rolling_avg = map_dbl(1:n(), function(i) {
      distances <- abs(as.numeric(datetime$mapped_datetime - mapped_datetime[i]))
      nearest_indices <- order(distances)[1:20]
      mean(datetime$occupancy_classifier[nearest_indices], na.rm = TRUE)
    })
  )

testProbs <- data.frame(Outcome = as.factor(dataTest$occupancy_classifier),
                        Probs = predict(model, dataTest, type= "response"))

auc_value <- auc(testProbs$Outcome, testProbs$Probs)

threshold <- 0.34  

dataTest_factor <- dataTest %>%
  mutate(occupancy_classifier = factor(occupancy_classifier, 
                                       levels = c(0, 1), 
                                       labels = c("Low", "High")))

testProbs <- testProbs %>%
  mutate(
    Predicted = ifelse(Probs >= threshold, "High", "Low"),
    Predicted = factor(Predicted, levels = c("Low", "High")), 
    Outcome = dataTest_factor$occupancy_classifier
  )


confusion_matrix <- confusionMatrix(testProbs$Predicted, testProbs$Outcome, positive = "High")

sensitivity <- confusion_matrix$byClass["Sensitivity"]
specificity <- confusion_matrix$byClass["Specificity"]

iterateThresholds <- function(data) {
  x = .01
  all_prediction <- data.frame()
  while (x <= 1) {
    
    this_prediction <-
      testProbs %>%
      mutate(predOutcome = ifelse(Probs > x, "High", "Low")) %>%
      count(predOutcome, Outcome) %>%
      summarize(True_Negative = sum(n[predOutcome=="Low" & Outcome=="Low"]),
                True_Positive = sum(n[predOutcome=="High" & Outcome=="High"]),
                False_Negative = sum(n[predOutcome=="Low" & Outcome=="High"]),
                False_Positive = sum(n[predOutcome=="High" & Outcome=="Low"])) %>%
      gather(Variable, Count) %>%
      mutate(Revenue =
               ifelse(Variable == "True_Negative", 0 * Count,
                      ifelse(Variable == "True_Positive", 2 * Count,
                             ifelse(Variable == "False_Negative", 0 * Count,
                                    ifelse(Variable == "False_Positive", (-1) * Count, 0)))),
             Threshold = x)
    
    all_prediction <- rbind(all_prediction, this_prediction)
    x <- x + .01
  }
  return(all_prediction)
}

whichThreshold <- iterateThresholds(testProbs)

whichThreshold_revenue <- 
  whichThreshold %>% 
  group_by(Threshold) %>% 
  summarize(Revenue = sum(Revenue))

optimal_threshold <- whichThreshold_revenue %>% 
  filter(Revenue == max(Revenue)) %>% 
  pull(Threshold)

results[[i]] <- list(
  sensitivity = sensitivity,
  specificity = specificity,
  optimal_threshold = optimal_threshold
)

cat("Iteration:", i, "Optimal Threshold:", optimal_threshold, "Sensitivity:", round(sensitivity, 4),
    "Specificity:", round(specificity, 4), "\n")
}

avg_optimal_threshold <- mean(sapply(results, function(res) res$optimal_threshold[1]), na.rm = T)
avg_sensitivity <- mean(sapply(results, function(res) res$sensitivity))
avg_specificity <- mean(sapply(results, function(res) res$specificity))

cat("Average Optimal Threshold over 100 runs:", avg_optimal_threshold, "\n")
cat("Average Sensitivity over 100 runs:", round(avg_sensitivity, 4), "\n")
cat("Average Specificity over 100 runs:", round(avg_specificity, 4), "\n")
```

